env: standard
runtime: nodejs10
# service: app-engine-react-demo
handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js|jpg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|jpg)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html